### ISSUE TITLE
Some Improvement Suggestions.

### ISSUE THREAD

**Issue by Aetopia** [Xt5gamerxX/Echo#1]
Just a few suggestions to make the source code cleaner.

1. Separate each tweak into its own module file.
2. Make some form of documentation that explains each tweak/s.

**Comment by ghost** [comment]
Thanks for the suggestions!

1. Echo is supposed to be a one click optimization utility, there is options for further customization

2. In the batch I have links and short descriptions but if you'd like me to make a documentation explaining each tweak I'll begin working on it now [:
